Repository sagalbot/vue-select, pull requests merged in 2020-03, with the labels that each got.

#1074 Fix spamming click on dropdown options.
  src/scss/global/_animations.scss
Labels: patch

#1049 * Add append-to-body directive and autoFocus option.
  docs/.vuepress/components/PositionedWithPopper.vue
  docs/.vuepress/config.js
  docs/api/props.md
  docs/guide/positioning.md
  docs/package.json
  docs/yarn.lock
  src/components/Select.vue
  src/directives/appendToBody.js
  tests/unit/Dropdown.spec.js
Labels: UX, enhancement, in progress, minor

#1038 Emit input event only if there is val to be deleted
  src/components/Select.vue
  tests/unit/Keydown.spec.js
Labels: bug
